### ISSUE TITLE
Duplicated light bulbs with same ids are detected

### ISSUE THREAD

**Issue by gaetan-puleo** [thomas-bouvier/yeelight-node#7]
Hello, thanks for your library it does a great job.

I just found a bug.

When I look for all the lightbulbs in my local network the lightbulbs are detected 2 times.

I will propose PR to fix it

**Comment by thomas-bouvier** [comment]
Hello @gaetan-puleo, many thanks for your contribution!

Will merge and release a new version :)

**Comment by gaetan-puleo** [comment]
thank you @thomas-bouvier  :pray:
